name: dcrn
config:
  dcrn:
    attention:
      modules:
        -
          type: inject
          inputs:
            - text_embedding
            - audio_features
          config:
            hidden_size: 512
            output_size: 256
    encoders:
      encoders:
        -
          name: text_embedding
          type: fc
        - 
          name: audio_features
          type: fc
    fusions:
      -
        modules:
          - 
            type: alfamix
    classify:
      - 0
      - 1
    losses:
      losses:
        - 
          type: alfamix
          weight: 0.1
          results:
            - 0
            - 1
        -
          type: focal
          weight: 1.0