name: utterance
config:
  utterance:
    attention:
      modules:
        -
          type: inject
          inputs:
            - text_embedding
            - audio_features
          config:
            hidden_size: 512
            output_size: 256
        -
          type: inject
          inputs:
            - text_embedding
            - primary_face_aus
          config:
            hidden_size: 512
            output_size: 256
    encoders:
      encoders:
        -
          name: text_embedding
          type: fc
          config:
            hidden_size: 128
            output_size: 64
        -
          name: audio_features
          type: fc
          config:
            hidden_size: 128
            output_size: 64
        -
          name: primary_face_aus
          type: rnn
    fusions:
      -
        modules:
          -
            type: alfamix
    classify:
      - 0
      - 1
    losses:
      losses:
        -
          type: avid
          weight: 0.05
          results: []
          stages:
            - 0
        -
          type: multilabelfocal
          weight: 1.0
