name: utterance
config:
  utterance:
    encoders:
      encoders:
        -
          name: text_embedding
          type: fc
          config:
            hidden_size: 128
            output_size: 64
        - 
          name: audio_features
          type: fc
          config:
            hidden_size: 128
            output_size: 64
        -
          name: primary_face_aus
          type: rnn
        -
          name: primary_face_landmark_graph
          type: mwmsg
    fusions:
      -
        modules:
          - 
            type: alfamix
    classify:
      - 0
      - 1
    losses:
      losses:
        - 
          type: avid
          weight: 0.01
          results: []
          stages:
            - 0
        -
          type: multilabelfocal
          weight: 1.0