experiment:
  name: ElderReact/[Utterance/Text,Audio,ActionUnits + Inject + AVID]
  store_path:  /panasas/scratch/grp-sreyasee/sidharth/stores/utterance
  workers: 28

  data: !ref data/elderreact.yaml

  model: !ref models/utterance-taau-avid.yaml

  train:
    epochs: 50
    learning_rate: 0.001
    optimizer:
        optimizer: Adam
        config:
            weight_decay: 0.0002
