experiment:
  name: ElderReact/[Utterance/Audio,ActionUnits + AVID]
  store_path:  /panasas/scratch/grp-sreyasee/sidharth/stores/affect
  workers: 28

  data: !ref data/elderreact.yaml

  model: !ref models/utterance-aau-avid.yaml

  train:
    epochs: 200
    learning_rate: 0.0005
    optimizer:
        optimizer: Adam
        config:
            weight_decay: 0.0002