experiment:
  name: IEMOCAP/[DialogCRN/Baseline]
  store_path:  /panasas/scratch/grp-sreyasee/sidharth/stores/affect
  workers: 6

  data: !ref data/iemocap-pyfeat.yaml

  model: !ref models/dcrn-baseline.yaml

  train:
    epochs: 200
    learning_rate: 0.0005
    optimizer:
        optimizer: Adam
        config:
            weight_decay: 0.0002