experiment:
  name: MELD/Utterance[Frames/Min]
  store_path: /panasas/scratch/grp-sreyasee/sidharth/stores/affect
  workers: 28

  data: !ref data/meld-utterance.yaml

  model: !ref models/utterance-f-min.yaml

  train:
    epochs: 100
    learning_rate: 0.0005
    optimizer: Adam
