experiment:
  name: MELD/BiDialogRNN
  store_path: /panasas/scratch/grp-sreyasee/sidharth/stores/affect
  workers: 28

  data: !ref data/meld.yaml

  model: !ref models/bidrnn.yaml

  train:
    epochs: 100
    learning_rate: 0.0005
    optimizer: Adam
