experiment:
  name: MELD/[DialogCRN/AU]
  store_path:  /panasas/scratch/grp-sreyasee/sidharth/stores/affect
  workers: 28

  data: !ref data/meld-pyfeat.yaml

  model: !ref models/dcrn-au.yaml

  train:
    epochs: 200
    learning_rate: 0.0005
    optimizer:
        optimizer: Adam
        config:
            weight_decay: 0.0002